 Test for radar spider

In [1]:
import pandas as pd

In [2]:
pwd

'/home/karen/Documents/GitHub/shinny'

In [3]:
expression_cell = pd.read_csv("data/single_cell/mean_expression_cell.csv", index_col=0)
expression_cell.head()

,Adipocyte,ArtEC,B-cell,B-plasma,CapEC,EnFB,Eosinophil,FB,Hyb,LymphEC,...,Specialised MF,T-cell,Tenocyte,VenEC,cDC1,cDC2,mSchwann,nmSchwann,pDC,most abundant in
Gene,,,,,,,,,,,,,,,,,,,,,
ACIN1,0.417506,0.209104,0.147946,0.207114,0.188800,0.174024,0.315649,0.232859,0.249706,0.180436,...,0.210590,0.222980,0.250792,0.203175,0.320608,0.223156,0.129569,0.169012,0.330829,Adipocyte
ADA,0.014123,0.149343,0.051087,0.211794,0.271267,0.036564,0.021994,0.183599,0.001473,0.029182,...,0.006037,0.082023,0.030694,0.072762,0.097412,0.110402,0.007948,0.024961,0.593198,pDC
AK1,0.033758,0.077454,0.004963,0.015381,0.046405,0.089141,0.000000,0.067482,0.057971,0.310814,...,0.095611,0.014278,0.068266,0.093459,0.022601,0.005838,0.098941,0.095709,0.000000,MF-IIsc(fg)
ALDOA,0.000000,0.170275,0.072773,0.188611,0.208669,0.151496,0.031045,0.130680,0.000000,0.230462,...,0.146612,0.118930,0.085669,0.220126,0.188399,0.213363,0.175072,0.075162,0.110334,MF-IIsc(fg)
AS3MT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001418,...,0.000367,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Mesothelium

In [4]:
expression_cell.columns

Index(['Adipocyte', 'ArtEC', 'B-cell', 'B-plasma', 'CapEC', 'EnFB',
       'Eosinophil', 'FB', 'Hyb', 'LymphEC', 'MF-I', 'MF-II', 'MF-IIsc(fg)',
       'MF-IIsn(fg)', 'MF-Isc(fg)', 'MF-Isn(fg)', 'Macrophage', 'Mast',
       'Mesothelium', 'Monocyte', 'MuSC', 'NK-cell', 'Neutrophil', 'Pericyte',
       'PnFB', 'RBC', 'SMC', 'Specialised MF', 'T-cell', 'Tenocyte', 'VenEC',
       'cDC1', 'cDC2', 'mSchwann', 'nmSchwann', 'pDC', 'most abundant in'],
      dtype='object')

In [5]:
cell_proportion = pd.read_csv("data/single_cell/proportion_cell_type.csv", index_col=0)
cell_proportion.head()

           Proportion
Cell Type
MF-I         0.229590
MF-II        0.155917
FB           0.152461
MuSC         0.110367
SMC          0.043945

In [6]:
expression_cell = expression_cell.drop(columns=["most abundant in"])
sum_expression_cell = expression_cell.sum()
sum_expression_gene = expression_cell.sum(axis=1)
sum_expression_gene

Gene
ACIN1       7.338225
ADA         2.728004
AK1         3.111199
ALDOA       6.944422
AS3MT       0.005630
BLCAP      11.143511
CA3        14.346652
CALM1      47.960682
CCNI       39.537113
CLIC4      13.185764
CLIC6       0.741470
CUTC       10.512179
EEF2       48.351036
EHMT1       7.205035
EIF3C      11.010674
ENO3       19.439166
ERI3        5.602769
FEZ2       17.410056
GLB1L       0.381922
GPX7        1.133903
HBA2        4.509185
HNRNPM     19.931910
KL          0.454228
KLRB1       2.647401
MAST1       0.082726
MB         24.627204
MEIS2       4.987768
MICU1       8.899819
MMP23B      0.743901
MYL2       22.120967
NDUFB4     26.772435
PARK7      30.855808
RECQL       4.840654
RNF7       14.956187
RPL13A     91.701693
RPS24      84.315425
SBDS       23.805578
SLC16A3     6.775356
STIM1       7.732088
STUM        0.520920
TAF9B       1.822598
TNNI1      14.962823
TPM3       35.764859
UBE2H      14.831318
dtype: float64

In [7]:
import plotly.express as px
import pandas as pd

In [10]:
def print_radar_spyder(gene="ALDOA", expression=None, categories = None):
       if expression is None:
              return None
       if categories is None:
              categories = ['Adipocyte', 'ArtEC', 'B-cell', 'B-plasma', 'CapEC', 'EnFB',
              'Eosinophil', 'FB', 'Hyb', 'LymphEC', 'MF-I', 'MF-II', 'MF-IIsc(fg)',
              'MF-IIsn(fg)', 'MF-Isc(fg)', 'MF-Isn(fg)', 'Macrophage', 'Mast',
              'Mesothelium', 'Monocyte', 'MuSC', 'NK-cell', 'Neutrophil', 'Pericyte',
              'PnFB', 'RBC', 'SMC', 'Specialised MF', 'T-cell', 'Tenocyte', 'VenEC',
              'cDC1', 'cDC2', 'mSchwann', 'nmSchwann', 'pDC']

       df = expression.loc[gene]
       df = pd.DataFrame(df)

       max_category = df[gene].idxmax()
    
       # Define color mapping
       color_map = {
              'Muscle Cells': 'red',
              'Lymphoid': 'blue',
              'Myeloid': 'blue',
              'Connective Tissue': 'orange',
              'Nervous System': 'purple',
              'Support Cells': 'yellow'
       }

       # Default to pink if not in the defined categories
       color = color_map.get(max_category, 'pink')

       fig = px.line_polar(df, r = gene, theta=categories, line_close=True)
       fig.update_traces(fill='toself', line=dict(color=color))
       #fig.show()
       return fig

In [11]:
def generate_goScatter(genes=["ALDOA"], expression=None, categories=None):
       if expression is None:
              return None
       if categories is None:
              categories = ['Adipocyte', 'ArtEC', 'B-cell', 'B-plasma', 'CapEC', 'EnFB',
              'Eosinophil', 'FB', 'Hyb', 'LymphEC', 'MF-I', 'MF-II', 'MF-IIsc(fg)',
              'MF-IIsn(fg)', 'MF-Isc(fg)', 'MF-Isn(fg)', 'Macrophage', 'Mast',
              'Mesothelium', 'Monocyte', 'MuSC', 'NK-cell', 'Neutrophil', 'Pericyte',
              'PnFB', 'RBC', 'SMC', 'Specialised MF', 'T-cell', 'Tenocyte', 'VenEC',
              'cDC1', 'cDC2', 'mSchwann', 'nmSchwann', 'pDC']
       #df = pd.DataFrame(df)
       fig = go.Figure()
       for gene in genes:
              fig.add_trace(go.Scatterpolar(r = expression.loc[gene], theta=categories, fill='toself', name = gene))
       return fig

In [12]:
proportion_cell_expression = expression_cell.div(sum_expression_gene.values,axis=0)

In [13]:
print_radar_spyder(gene="ALDOA", expression=expression_cell)

In [14]:
expression_cell.index

Index(['ACIN1', 'ADA', 'AK1', 'ALDOA', 'AS3MT', 'BLCAP', 'CA3', 'CALM1',
       'CCNI', 'CLIC4', 'CLIC6', 'CUTC', 'EEF2', 'EHMT1', 'EIF3C', 'ENO3',
       'ERI3', 'FEZ2', 'GLB1L', 'GPX7', 'HBA2', 'HNRNPM', 'KL', 'KLRB1',
       'MAST1', 'MB', 'MEIS2', 'MICU1', 'MMP23B', 'MYL2', 'NDUFB4', 'PARK7',
       'RECQL', 'RNF7', 'RPL13A', 'RPS24', 'SBDS', 'SLC16A3', 'STIM1', 'STUM',
       'TAF9B', 'TNNI1', 'TPM3', 'UBE2H'],
      dtype='object', name='Gene')

In [15]:
cells= ['Adipocyte', 'ArtEC', 'B-cell', 'B-plasma', 'CapEC', 'EnFB',
              'Eosinophil', 'FB', 'Hyb', 'LymphEC', 'MF-I', 'MF-II', 'MF-IIsc(fg)',
              'MF-IIsn(fg)', 'MF-Isc(fg)', 'MF-Isn(fg)', 'Macrophage', 'Mast',
              'Mesothelium', 'Monocyte', 'MuSC', 'NK-cell', 'Neutrophil', 'Pericyte',
              'PnFB', 'RBC', 'SMC', 'Specialised MF', 'T-cell', 'Tenocyte', 'VenEC',
              'cDC1', 'cDC2', 'mSchwann', 'nmSchwann', 'pDC']

In [16]:
import plotly.graph_objects as go

generate_goScatter(genes = ['ACIN1', 'MYL2', 'FEZ2', 'ALDOA'], expression=proportion_cell_expression)

In [17]:
cell_groups = pd.read_csv("data/single_cell/Cell_type_classification.csv")
cell_groups

,Abbreviation,Full Name,Group Classification,Higher-Level Grouping,Classification
0,EnFB,Endomysial Fibroblast,Fibroblasts,Connective Tissue,Connective Tissue
1,FB,Fibroblast,Fibroblasts,Connective Tissue,Connective Tissue
2,PnFB,Perineurial Fibroblast,Fibroblasts,Connective Tissue,Connective Tissue
3,Tenocyte,Tenocyte,Tendon Cells,Connective Tissue,Connective Tissue
4,B-cell,B Lymphocyte,Immune Cells,Immune System,Lymphoid
5,B-plasma,Plasma B Cell,Immune Cells,Immune System,Lymphoid
6,NK-cell,Natural Killer Cell,Immune Cells,Immune System,Lymphoid
7,Hyb,Hybrid Myofiber,Myofibers,Muscle Cells,Muscle Cells
8,MF-I,Myofiber Type I,Myofibers,Muscle Cells,Muscle Cells
9,MF-II,Myofiber Type II,Myofibers,Muscle Cells,Muscle Cells
10,MF-IIsc(fg),Myofiber Type II Subcluster (fast glycolytic),Myofibers,Muscle Cells,Muscle Cells
11,MF-IIsn(fg),Myofiber Type II Subcluster (slow oxidative),Myofibers,Muscle Cells,Muscle Cells
12,MF-Isc(fg),Myofiber Type I Subcluster (fast glycolytic),Myofibers,Muscle Cells,Muscle Cells
13,MF-Isn(fg),Myofiber Type I Subcluster (slow oxidative),Myofibers,Muscle Cells,Muscle Cells
14,SMC,Smooth Muscle Cell,Muscle Cells,Muscle Cells,Muscle Cells
15,MuSC,Muscle Stem Cell,Stem Cells,Progenitor/Stem Cells,Muscle Cells
16,cDC1,Conventional Dendritic Cell Type 1,Immune Cells,Immune System,Myeloid
17,cDC2,Conventional Dendritic Cell Type 2,Immune Cells,Immune System,Myeloid
18,Eosinophil,Eosinophil,Immune Cells,Immune System,Myeloid
19,Macrophage,Macrophage,Immune Cells,Immune System,Myeloid
20,Mast,Mast Cell,Immune Cells,Immune System,Myeloid
21,Monocyte,Monocyte,Immune Cells,Immune System,Myeloid
22,Neutrophil,Neutrophil,Immune Cells,Immune System,Myeloid
23,pDC,Plasmacytoid Dendritic Cell,Immune Cells,Immune System,Myeloid
24,Specialised MF,Specialized Macrophage,Immune Cells,Immune System,Myeloid
25,T-cell,T Lymphocyte,Immune Cells,Immune System,Myeloid
26,mSchwann,Myelinating Schwann Cell,Glial Cells,Nervous System,Nervous System
27,nmSchwann,Non-Myelinating Schwann Cell,Glial Cells,Nervous System,Nervous System
28,RBC,Red Blood Cell,Blood Cells,Circulatory System,Red Blood Cell
29,Adipocyte,Adipocyte,Stromal Cells,Support Cells,Support Cells
30,Mesothelium,Mesothelial Cell,Mesothelial Cells,Support Cells,Support Cells
31,ArtEC,Arterial Endothelial Cell,Endothelial Cells,Vascular Cells,Vascular Cells
32,CapEC,Capillary Endothelial Cell,Endothelial Cells,Vascular Cells,Vascular Cells
33,LymphEC,Lymphatic Endothelial Cell,Endothelial Cells,Vascular Cells,Vascular Cells
34,Pericyte,Pericyte,Perivascular Cells,Vascular Cells,Vascular Cells
35,VenEC,Venous Endothelial Cell,Endothelial Cells,Vascular Cells,Vascular Cells

In [18]:

# Rename columns using dataframe B
A = expression_cell.rename(columns=dict(zip(cell_groups['Abbreviation'], cell_groups['Classification'])))

# Sum columns with the same name
A = A.groupby(level=0, axis=1).sum()
A.head()

/tmp/ipykernel_268801/1780591889.py:5: FutureWarning:

DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.

,Connective Tissue,Lymphoid,Muscle Cells,Myeloid,Nervous System,Red Blood Cell,Support Cells,Vascular Cells
Gene,,,,,,,,
ACIN1,0.811384,0.611670,1.567632,2.369213,0.298581,0.125104,0.616409,0.938233
ADA,0.253970,0.418511,0.027385,1.161621,0.032909,0.000000,0.022080,0.811529
AK1,0.301947,0.026792,1.676427,0.171675,0.194650,0.065073,0.092971,0.581665
ALDOA,0.501847,0.372718,3.197685,1.339121,0.250235,0.000000,0.160352,1.122465
AS3MT,0.000000,0.000000,0.001111,0.000367,0.000000,0.000000,0.002293,0.001859

In [19]:
cells = A.columns.to_list()

In [24]:
for gene in A.index :
    fig = print_radar_spyder(gene=gene, expression=A, categories=cells)
    print(gene)
    fig.show()

ACIN1

ADA

AK1

ALDOA

AS3MT

BLCAP

CA3

CALM1

CCNI

CLIC4

CLIC6

CUTC

EEF2

EHMT1

EIF3C

ENO3

ERI3

FEZ2

GLB1L

GPX7

HBA2

HNRNPM

KL

KLRB1

MAST1

MB

MEIS2

MICU1

MMP23B

MYL2

NDUFB4

PARK7

RECQL

RNF7

RPL13A

RPS24

SBDS

SLC16A3

STIM1

STUM

TAF9B

TNNI1

TPM3

UBE2H

In [104]:
print_radar_spyder(gene="MYL2", expression=A, categories=cells)

In [101]:
generate_goScatter(genes = ['ACIN1', 'MYL2', 'FEZ2', 'ALDOA'], expression=A, categories=cells)

In [102]:
compact_expression_proportion = A.div(sum_expression_gene.values,axis=0)

In [103]:
generate_goScatter(genes = ['ACIN1', 'MYL2', 'FEZ2', 'ALDOA'], expression=compact_expression_proportion, categories=cells)